version: "3.8"
services:
   web:
      build: .
      container_name: flask_dash_app
      ports:
         - "5000:5000"
      volumes:
         - .:/app
      environment:
         - FLASK_APP=app/__init__.py:server
      command: flask run --host=0.0.0.0

   mongo:
      image: mongo:latest
      container_name: mongo_db
      environment:
         MONGO_INITDB_ROOT_USERNAME: admin
         MONGO_INITDB_ROOT_PASSWORD: admin
      ports:
         - "27017:27017"
      volumes:
         - mongo_data:/data/db

   redis:
      image: redis:latest
      container_name: redis_server
      ports:
         - "6379:6379"

volumes:
   mongo_data:
